name: Hello world

on:
  push:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Execute code directly inside the workflow
        run: echo "Hello world"
